r"""Embed shared/extract.js into the C and Racket sources.

  python embed.py            (paths relative to this file's directory)

Writes
  c/src/extract_js.h      EXTRACT_JS_PARTS[]: NULL-terminated array of C string literals, each <= 2000
                          bytes of *source text*; the C side concatenates them (strlen sum -> one buffer).
                          Bytes are escaped so the concatenation is byte-identical to extract.js:
                          printable ASCII as is (\\ and " escaped), tab/newline as \t \n, every other
                          byte (including all UTF-8 bytes >= 0x80) as an octal escape \ooo (octal is
                          used instead of \xNN because \x escapes greedily swallow following hex digits).
                          Also EXTRACT_JS_SHA256 (hex) and EXTRACT_JS_SIZE (bytes) for self-checks.
  racket/extract-js.rkt   (provide extract-js extract-js-sha256): one Racket string literal; the source
                          is UTF-8 with #lang racket/base, non-ASCII characters written raw, \\ and "
                          escaped, control characters as \\uXXXX.  string->bytes/utf-8 of it is
                          byte-identical to extract.js (verified by dev-tools/embed_roundtrip.cmd).
"""
import os, sys, hashlib

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(HERE, "extract.js")
C_OUT = os.path.join(ROOT, "c", "src", "extract_js.h")
RKT_OUT = os.path.join(ROOT, "racket", "extract-js.rkt")
CHUNK = 2000

def c_escape_byte(b):
    if b == 0x5C: return "\\\\"
    if b == 0x22: return "\\\""
    if b == 0x0A: return "\\n"
    if b == 0x09: return "\\t"
    if 0x20 <= b < 0x7F and b != 0x3F:   # '?' escaped too, so no trigraph sequences can form
        return chr(b)
    return "\\%03o" % b

def c_chunks(data):
    """Split into string literals whose *source text* (escapes included) is <= CHUNK bytes each."""
    parts, cur, cur_len = [], [], 0
    for b in data:
        e = c_escape_byte(b)
        if cur_len + len(e) > CHUNK:
            parts.append("".join(cur)); cur, cur_len = [], 0
        cur.append(e); cur_len += len(e)
    if cur: parts.append("".join(cur))
    return parts

def racket_escape(text):
    out = []
    for ch in text:
        o = ord(ch)
        if ch == "\\": out.append("\\\\")
        elif ch == '"': out.append('\\"')
        elif ch == "\n": out.append("\\n")
        elif ch == "\t": out.append("\\t")
        elif o < 0x20 or o == 0x7F: out.append("\\u%04X" % o)
        else: out.append(ch)
    return "".join(out)

def main():
    data = open(SRC, "rb").read()
    if b"\r" in data:
        print("note: extract.js contains CR bytes; they are embedded verbatim", file=sys.stderr)
    text = data.decode("utf-8")
    sha = hashlib.sha256(data).hexdigest()
    parts = c_chunks(data)
    lines = ["/* Generated by shared/embed.py from shared/extract.js -- DO NOT EDIT. */",
             "#ifndef EXTRACT_JS_H", "#define EXTRACT_JS_H",
             "#define EXTRACT_JS_SIZE %dUL" % len(data),
             "#define EXTRACT_JS_SHA256 \"%s\"" % sha,
             "/* Concatenate all parts (NULL-terminated) to obtain the byte-identical extract.js source. */",
             "static const char *const EXTRACT_JS_PARTS[] = {"]
    for p in parts: lines.append("  \"%s\"," % p)
    lines.append("  (const char *)0"); lines.append("};"); lines.append("#endif")
    if os.path.isdir(os.path.dirname(C_OUT)):
        with open(C_OUT, "w", encoding="ascii", newline="\n") as f: f.write("\n".join(lines) + "\n")
    rkt = ["#lang racket/base",
           ";; Generated by shared/embed.py from shared/extract.js -- DO NOT EDIT.",
           "(provide extract-js extract-js-sha256 extract-js-size)",
           "(define extract-js-sha256 \"%s\")" % sha,
           "(define extract-js-size %d)" % len(data),
           "(define extract-js \"%s\")" % racket_escape(text)]
    with open(RKT_OUT, "w", encoding="utf-8", newline="\n") as f: f.write("\n".join(rkt) + "\n")
    print("extract.js: %d bytes sha256 %s" % (len(data), sha))
    if os.path.exists(C_OUT): print("wrote %s (%d parts, %d bytes)" % (C_OUT, len(parts), os.path.getsize(C_OUT)))
    print("wrote %s (%d bytes)" % (RKT_OUT, os.path.getsize(RKT_OUT)))

if __name__ == "__main__":
    main()
